apiVersion: v1
entries:
  squidex:
  - apiVersion: v2
    appVersion: 5.8.0
    created: "2021-08-10T01:05:55.262103-03:00"
    dependencies:
    - condition: mongodb-replicaset.enabled
      name: mongodb-replicaset
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 3.9.6
    description: Squidex CMS
    digest: 4089126bc4c7bd5c96d03820458a1352d74ae19b9843146b92e2d9d4507de8b6
    home: https://squidex.io/
    keywords:
    - cms
    - headless-cms
    - mongodb
    - csharp
    - asp-net-core
    - asp-net
    name: squidex
    sources:
    - https://github.com/Squidex/squidex
    type: application
    urls:
    - https://squidex.github.io/squidex/helm/squidex-1.0.0.tgz
    version: 1.0.0
generated: "2021-08-10T01:05:55.259799-03:00"
